%{
 * Standartni/Vedecka (graficka) kalkulacka
 *
 * @author  Vaclav Pastusek
 * @login   xpastu02
 * @date    28.05.2020
%}
close all;
clear variables;
clc;

% zkouska:
% gamma(log2(5))*sin(1+2./cos((1.2e0):(((pi/4))):20.1*pi)).^2+1

%________________________________main____________________________________
% prirazeni funkci
func = calcFunctions;

% pozice figure
posF = [100 50 535 432];
fig = figure('NumberTitle','off','Position',posF,...
   'name','Calculator','Resize','off',...
   'ToolBar','none','MenuBar','none',...
   'WindowKeyReleaseFcn', @func.keyPressF);

% panel na graf
panel = uipanel(fig,'unit','pix','Position',[20 352 500 340],...
   'Tag','panel','Visible','off');
axes(panel)

% edit na prikazovy radek
edit = uicontrol(fig,'Style','edit',...
   'FontSize',20,'FontName','Gotham',...
   'Tag','edit',...
   'Position',[20 290 500 60]);

% prvni skupina kruhovych tlacitek
bg1 = uibuttongroup(fig,'Visible','on',...
   'unit','pix','Position',[20 posF(4)-80 100 75],...
   'Tag','bg1',...
   'SelectionChangedFcn',@func.bselection1);
text1 = uicontrol(bg1, 'Style', 'text',...
   'String','Language','Tag','lang',...
   'Position',[0 50 80 20]);
r1 = uicontrol(bg1,'Style',...
   'radiobutton',...
   'String','English',...
   'Tag', 'en',...
   'Position',[10 25 100 30],...
   'HandleVisibility','off');
r2 = uicontrol(bg1,'Style','radiobutton',...
   'String','Èeština',...
   'Tag', 'cz',...
   'Position',[10 0 100 30],...
   'HandleVisibility','off');

% druha skupina kruhovych tlacitek
bg2 = uibuttongroup(fig,'Visible','on',...
   'unit','pix','Position',[120 posF(4)-80 100 75],...
   'Tag','bg2',...
   'SelectionChangedFcn',@func.bselection2);
text2 = uicontrol(bg2, 'Style', 'text',...
   'String','Graph','Tag','graph',...
   'Position',[0 50 80 20]);
r3 = uicontrol(bg2,'Style', 'radiobutton',...
   'String','Off',...
   'Tag', 'off',...
   'Position',[10 25 100 30],...
   'HandleVisibility','off');
r4 = uicontrol(bg2,'Style','radiobutton',...
   'String','On',...
   'Tag', 'on',...
   'Position',[10 0 100 30],...
   'HandleVisibility','off');

% treti skupina kruhovych tlacitek
bg3 = uibuttongroup(fig,'Visible','on',...
   'unit','pix','Position',[220 posF(4)-80 100 75],...
   'Tag','bg3',...
   'SelectionChangedFcn',@func.bselection3);
text3 = uicontrol(bg3, 'Style', 'text',...
   'String','Type','Tag','type',...
   'Position',[0 55 80 15]);
r5 = uicontrol(bg3,'Style', 'radiobutton',...
   'String','Classic',...
   'Tag', 'cla',...
   'Position',[10 25 100 30],...
   'HandleVisibility','off');
r6 = uicontrol(bg3,'Style','radiobutton',...
   'String','Scientific',...
   'Tag', 'sci',...
   'Position',[10 0 100 30],...
   'HandleVisibility','off');

% ctvrta skupina kruhovych tlacitek
bg4 = uibuttongroup(fig,'Visible','on',...
   'unit','pix','Position',[320 posF(4)-80 100 75],...
   'Tag','bg4',...
   'SelectionChangedFcn',@func.bselection4);
text4 = uicontrol(bg4, 'Style', 'text',...
   'String','Optimalization','Tag','optim',...
   'Position',[0 55 95 15]);
r7 = uicontrol(bg4,'Style', 'radiobutton',...
   'String','Off',...
   'Tag', 'off',...
   'Position',[10 25 100 30],...
   'HandleVisibility','off');
r8 = uicontrol(bg4,'Style','radiobutton',...
   'String','On',...
   'Tag', 'on',...
   'Position',[10 0 100 30],...
   'HandleVisibility','off');

% pata skupina kruhovych tlacitek
bg5 = uibuttongroup(fig,'Visible','on',...
   'unit','pix','Position',[420 posF(4)-80 100 75],...
   'Tag','bg5',...
   'SelectionChangedFcn',@func.bselection5);
text5 = uicontrol(bg5, 'Style', 'text',...
   'String','Dark mode','Tag','mode',...
   'Position',[0 55 95 15]);
r9 = uicontrol(bg5,'Style', 'radiobutton',...
   'String','Off',...
   'Tag', 'off',...
   'Position',[10 25 100 30],...
   'HandleVisibility','off');
r10 = uicontrol(bg5,'Style','radiobutton',...
   'String','On',...
   'Tag', 'on',...
   'Position',[10 0 100 30],...
   'HandleVisibility','off');

% data
fig.UserData.editD = '';
fig.UserData.optD = 1;
fig.UserData.darkM = 0;
fig.UserData.color.white = [1 1 1];
fig.UserData.color.black = [0.05 0.05 0.05];
fig.UserData.color.darkgray = [0.08 0.08 0.08];
fig.UserData.color.gray = [0.128 0.128 0.128];
fig.UserData.color.green = [0.15 0.75 0.15];
blue = [0.05 0.05 1];
fig.UserData.color.blue = blue;
fig.UserData.color.darkwhite = [0.9400 0.9400 0.9400];
fig.UserData.color.shadow = [0.7000 0.7000 0.7000];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% klasicka kalkulacka
% vytvoreni a umisteni tlacitek
for j = 0:3
   for i = 0:4
      pushbutton = uicontrol('Style', 'pushbutton',...
         'Position', [20+i*100 220-j*70 100 70],...
         'FontSize',20,'FontName','Gotham',...
         'ForegroundColor',blue,...
         'Tag', int2str(i+j*5));
   end
end

% nalezeni tlacitek
button = flipud(findall(0,'-regexp','Tag','^\d+$'));

% pridani stringu a callbacku numerickym tlacitkum
for i = 1:15
   if mod(i-1,5) < 3
      button(i).String = num2str(i+6-8*fix((i-1)/5));
      button(i).Callback = {@func.pushNumB,button(i).String};
   end
end

% definovani ostatnich tlacitek
otherButtons=cell(1,20);
otherButtons(:)={''};
otherButtons(mod(0:14,5) > 2)={'DEL','AC','*','/','+','-'};
otherButtons(16:20)={'0','.','E','Ans','='};

% pridani stringu a callbacku ostatnim tlacitkum
for i = 1:20
   if mod(i-1,5) > 2 || i > 15
      button(i).String = cell2mat(otherButtons(i));
      nameB = button(i).String;
      % pridani callbacku pro cislo 0 a jine znaky
      if nameB == '0'
         button(i).Callback = {@func.pushNumB,nameB};
      else
         button(i).Callback = {@func.pushClaB,nameB};
      end
   end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% vedecka kalkulacka
% vytvoreni a umisteni tlacitek
for j = 0:3
   for i = 0:4
      pushbuttonSci = uicontrol('Style', 'pushbutton',...
         'Position', [520+i*100 220-j*70 100 70],...
         'FontSize',12,'FontName','Gotham',...
         'ForegroundColor',blue,'Visible','off',...
         'Tag', strcat('sci',int2str(i+j*5)));
   end
end

% nalezeni tlacitek
buttonSci = flipud(findall(0,'-regexp','Tag','^sci\d+$'));

% definovani tlacitek
allButtonsSci={'sin(x)','cos(x)','tan(x)','cot(x)',char(960),...
   'log(x)',strcat('log',char(8321),char(8320),'(x)'),strcat('log',char(8322),'(x)'),'gamma(x)','e',...
   'x!','|x|','<html>x<sup>y','sqrt(x)','()',...
   '<html>e<sup>x','<html>10<sup>x','asin(x)','acos(x)','atan(x)'};

% pridani callbacku
for i = 1:20
   buttonSci(i).String = allButtonsSci(i);
   nameB = allButtonsSci(i);
   buttonSci(i).Callback = {@func.pushSciB,cell2mat(nameB)};
end